---
name: 'Bump up npm dependencies'
on:
  schedule:
    - cron: '0 1,13 * * *'
  workflow_dispatch:

jobs:
  check:
    name: 'Check npm dependencies update'
    runs-on: ubuntu-latest
    steps:
      - name: 'Check out the develop branch'
        uses: actions/checkout@v3
        with:
          ref: develop
      - name: 'Setup node.js'
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - run: npm --silent --no-progress --no-color --audit=false install -g npm-check-updates
      - name: 'Check npm updates'
        id: check
        # we capture the exit code without failing the step, otherwise the entire action fails, even if the next (/last) job succeeded
        run: |
          set +e
          ncu --errorLevel 2 --reject jest,@types/jest
          echo ::set-output name=exit_code::$?
          set -e
  update:
    name: 'Update npm dependencies'
    runs-on: ubuntu-latest
    needs: check
    if: needs.check.steps.check.outputs.exit_code == 1
    # ncu return non-zero if there is any npm dependency update detected
    steps:
      - name: 'Check out the develop branch'
        uses: actions/checkout@v3
        # here we need both of develop and main branches because of git-flow
        with:
          fetch-depth: 0
      - name: 'Set Github user'
        run: |
          git config user.email "zhaow.km@gmail.com"
          git config user.name "Zhao Wang"
          sudo apt-get install -qq -o=Dpkg::Use-Pty=0 git-flow
          git config gitflow.branch.master main
          git config gitflow.branch.main main
          git config gitflow.branch.develop develop
          git config gitflow.prefix.feature feature/
          git config gitflow.prefix.bugfix bugfix/
          git config gitflow.prefix.release release/
          git config gitflow.prefix.hotfix hotfix/
          git config gitflow.prefix.support support/
          git config gitflow.prefix.versiontag v
          git checkout develop
      - name: 'Setup node.js'
        uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: https://registry.npmjs.org/
      - run: npm --silent --no-progress --no-color --audit=false install -g npm-check-updates
      - name: 'Setup Python'
        uses: actions/setup-python@v3
        with:
          python-version: '3.9'
      - run: pip install bumpsemver --quiet
      - name: 'Bump up npm dependencies'
        run: ncu --errorLevel 1 --reject jest,@types/jest --upgrade
      - name: 'Build'
        id: build
        run: |
          set -e
          npm --silent --no-progress --no-color --audit=false install
          npm --no-progress --no-color exec tsc
          echo ::set-output name=exit_code::$?
      - name: 'Test'
        id: test
        if: steps.build.outputs.exit_code == 0
        run: |
          npm run test
          echo ::set-output name=exit_code::$?
      - name: 'Bump package version'
        id: bump
        if: steps.test.outputs.exit_code == 0
        run: |
          set -e
          export GIT_MERGE_AUTOEDIT=no
          msg="chore: bumped up npm dependencies"
          git add package.json package-lock.json
          git commit -m "${msg}"
          bumpsemver patch
          branch_name=$(cat .bumpsemver.cfg |grep "current_version ="| awk '{print $3}')
          git flow release start ${branch_name}
          head_ref=$(git rev-parse --abbrev-ref HEAD)
          branch_name=${head_ref//release\//}
          git flow release finish -m "${msg}" ${branch_name}
          git push origin develop main --tag
          unset GIT_MERGE_AUTOEDIT
          echo ::set-output name=exit_code::$?
      - name: 'Publish'
        run: npm --no-progress --no-color publish --access public
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
